### PR TITLE
feat: add test for installing plugins

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Review by garethjevans — APPROVED** [review]

**Comment by cagiti** [comment]
The checks only run on merge to master I take it?

**Comment by garethjevans** [comment]
no, they should run for all PRs, no idea why they are not

**Comment by cagiti** [comment]
Perhaps it's down to the work they're carrying out this week, I've seen a notice somewhere that GitHub actions might experience delays in execution

**Comment by garethjevans** [comment]
Currently failing on the latest rebase with `ERROR: admin is missing the Overall/Administer permission`

**Pull request merged**
